name: CI/CD on push to production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
                    ps -aux | grep git_dis+ | grep python3 | awk '{print $2}' | xargs sudo kill
                    ls
                    cd chatGptDiscord
                    make install
                    make refresh
                    source venv/bin/activate
                    python3 main.py

