name: CI/CD on push to production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
                    echo "killall -9 python3"
                    killall -9 python3
                    echo "ls"
                    ls
                    echo "cd chatGptDiscord"
                    cd chatGptDiscord
                    echo "install"
                    make install
                    echo "refresh"
                    make refresh
                    echo "venv/bin/activate"
                    source venv/bin/activate
                    echo "main.py"
                    python3 main.py
