name: CI/CD on push to production

on:
  push:
    branches:
      - add_docker

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
                    sudo apt-get install ffmpeg
                    sudo docker pull gcr.io/bot-discord-390015/discord
                    sudo docker run gcr.io/bot-discord-390015/discord